import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Main from '../src/components/main'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Star Guardian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Main />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
